# Generated by Django 5.1.2 on 2024-10-25 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 10, 25, 6, 55, 33, 127229, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
