# Generated by Django 5.1.2 on 2024-11-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_properties', models.PositiveIntegerField(default=0)),
                ('active_tenants', models.PositiveIntegerField(default=0)),
                ('pending_maintenance_requests', models.PositiveIntegerField(default=0)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
